spring.application.name=expense-platform
spring.datasource.url=jdbc:postgresql://localhost:8081/mydatabase
spring.datasource.username=postgre
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver # Spring Boot can infer this from the URL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect